# Generated by Django 4.2.16 on 2026-03-25 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanceDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Окончание')),
                ('title', models.CharField(max_length=200, verbose_name='Название группы / занятия')),
                ('teacher_name', models.CharField(blank=True, max_length=120, verbose_name='Преподаватель')),
                ('room', models.CharField(blank=True, max_length=120, verbose_name='Зал / кабинет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_classes', to='studio.dancedirection', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Занятие в расписании',
                'verbose_name_plural': 'Расписание',
                'ordering': ['weekday', 'start_time', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Обращение с сайта',
                'verbose_name_plural': 'Обращения с сайта',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='studio_cont_created_990fb5_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrialApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('preferred_time_note', models.CharField(blank=True, max_length=300, verbose_name='Удобное время (комментарий)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('preferred_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_applications', to='studio.dancedirection', verbose_name='Интересующее направление')),
            ],
            options={
                'verbose_name': 'Заявка на пробное',
                'verbose_name_plural': 'Заявки на пробное',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='studio_tria_created_0930fc_idx')],
            },
        ),
    ]
