# Generated by Django 4.2.16 on 2026-04-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyclass',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'Слот расписания', 'verbose_name_plural': 'Слоты расписания'},
        ),
        migrations.RemoveField(
            model_name='weeklyclass',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='weeklyclass',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='weeklyclass',
            name='teacher_name',
        ),
        migrations.RemoveField(
            model_name='weeklyclass',
            name='title',
        ),
        migrations.CreateModel(
            name='DanceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('teacher_name', models.CharField(blank=True, max_length=120, verbose_name='Преподаватель')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='studio.dancedirection', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='weeklyclass',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='studio.dancegroup', verbose_name='Группа'),
        ),
    ]
