# Generated by Django 4.2.16 on 2026-04-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_weeklyclass_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dancegroup',
            name='direction',
        ),
        migrations.AddField(
            model_name='weeklyclass',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_classes', to='studio.dancedirection', verbose_name='Направление'),
        ),
    ]
