# Generated by Django 4.2.16 on 2026-04-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_remove_dancegroup_direction_weeklyclass_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dancegroup',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='weeklyclass',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Преподаватель'),
        ),
    ]
