# Generated by Django 4.2.16 on 2026-04-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_remove_dancegroup_teacher_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancedirection',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендуется горизонтальное фото. Размер подгоняется автоматически.', null=True, upload_to='directions/', verbose_name='Обложка'),
        ),
    ]
