# Generated by Django 4.2.16 on 2026-04-02 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import studio.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studio', '0005_dancedirection_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=25, validators=[studio.models.validate_ru_phone], verbose_name='Телефон')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='studio.dancegroup', verbose_name='Группа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль ученика',
                'verbose_name_plural': 'Профили учеников',
            },
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_due_date', models.DateField(verbose_name='Дата оплаты')),
                ('show_reminder', models.BooleanField(default=True, help_text='Снимите галочку после того, как ученик произвёл оплату.', verbose_name='Показывать напоминание')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='studio.studentprofile', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Напоминание об оплате',
                'verbose_name_plural': 'Напоминания об оплате',
                'ordering': ['payment_due_date'],
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=25, validators=[studio.models.validate_ru_phone], verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль родителя',
                'verbose_name_plural': 'Профили родителей',
            },
        ),
        migrations.CreateModel(
            name='ChildRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='ФИО ребёнка')),
                ('group', models.ForeignKey(blank=True, help_text='Если аккаунт ученика указан — группа берётся оттуда.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_records', to='studio.dancegroup', verbose_name='Группа')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='studio.parentprofile', verbose_name='Родитель')),
                ('student', models.ForeignKey(blank=True, help_text='Заполняется администратором, если ребёнок зарегистрирован на сайте.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_links', to='studio.studentprofile', verbose_name='Аккаунт ученика')),
            ],
            options={
                'verbose_name': 'Ребёнок родителя',
                'verbose_name_plural': 'Дети родителей',
                'ordering': ['full_name'],
            },
        ),
    ]
