# Generated by Django 4.2.16 on 2026-04-15 14:42

from django.db import migrations, models
import studio.models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_studentprofile_paymentreminder_parentprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=25, validators=[studio.models.validate_ru_phone], verbose_name='Телефон'),
        ),
    ]
