# Generated by Django 4.2.16 on 2026-04-30 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_password_reset_code_and_hints'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='achievements/covers/', verbose_name='Обложка')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Альбом достижений',
                'verbose_name_plural': 'Альбомы достижений',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AchievementPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='achievements/photos/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=220, verbose_name='Подпись')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='studio.achievementalbum', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фото достижения',
                'verbose_name_plural': 'Фото достижений',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
