# Generated by Django 4.2.16 on 2026-05-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_achievementalbum_achievementphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Указывается при регистрации; для лиц 18+ на аккаунте должен быть email для уведомлений об оплате.', null=True, verbose_name='Дата рождения'),
        ),
    ]
