# Generated by Django 4.2.16 on 2026-05-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_studentprofile_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма, ₽')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('succeeded', 'Оплачено'), ('canceled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('yookassa_payment_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='ID платежа ЮKassa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_payments', to='studio.studentprofile', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Онлайн-оплата',
                'verbose_name_plural': 'Онлайн-оплаты',
                'ordering': ['-created_at'],
            },
        ),
    ]
