# Generated by Django 4.2.16 on 2026-06-03 15:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import studio.models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0013_paymentreminder_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreminder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=studio.models.default_reminder_amount, help_text='От 1 до 100 000 ₽. Уходит в ЮKassa при онлайн-оплате.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('100000.00'))], verbose_name='Сумма к оплате, ₽'),
        ),
        migrations.AlterField(
            model_name='paymentreminder',
            name='show_reminder',
            field=models.BooleanField(default=True, verbose_name='Показывать напоминание'),
        ),
    ]
