# Generated by Django 4.2.16 on 2026-06-03 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0014_paymentreminder_amount_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('role', models.CharField(blank=True, help_text='Например: «Современный танец» или «Классическая хореография».', max_length=160, verbose_name='Специализация / направление')),
                ('bio', models.TextField(blank=True, verbose_name='Краткая информация')),
                ('photo', models.ImageField(blank=True, help_text='Квадратное фото смотрится лучше всего — выводится в круглой рамке.', null=True, upload_to='trainers/', verbose_name='Фото')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
                'ordering': ['sort_order', 'full_name'],
            },
        ),
        migrations.AlterField(
            model_name='weeklyclass',
            name='teacher_name',
            field=models.CharField(blank=True, help_text='Используется, только если тренер не выбран из списка.', max_length=120, verbose_name='Преподаватель (текстом)'),
        ),
        migrations.AddField(
            model_name='weeklyclass',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_classes', to='studio.trainer', verbose_name='Тренер'),
        ),
    ]
