# Generated by Django 4.2.16 on 2026-06-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0018_studiohall_weeklyclass_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите фото и настройте кадрирование ползунками или кликом по превью в админке.', null=True, upload_to='trainers/', verbose_name='Фото'),
        ),
    ]
