"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from decimal import Decimal
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Загружаем переменные окружения из файла .env (если он есть).
# Реальные секреты хранятся только там и в репозиторий не попадают.
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    """Читает булеву переменную окружения ('True'/'1'/'yes' → True)."""
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=None):
    """Читает список через запятую (например ALLOWED_HOSTS)."""
    value = os.environ.get(name)
    if not value:
        return default or []
    return [item.strip() for item in value.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', False)

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', ['127.0.0.1', 'localhost'])


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'studio',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise: отдаёт статику самим Django (без отдельной настройки nginx).
    # Должен идти сразу после SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'studio.context_processors.payment_reminder',
                'studio.context_processors.trial_form',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = []
# Куда collectstatic собирает статику для боевого сервера.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Хранилища файлов. На боевом сервере (DEBUG=False) статику отдаёт WhiteNoise
# со сжатием и кешированием. Локально (DEBUG=True) — обычное хранилище,
# чтобы не требовался запуск collectstatic при разработке.
_staticfiles_backend = (
    'django.contrib.staticfiles.storage.StaticFilesStorage'
    if DEBUG
    else 'whitenoise.storage.CompressedStaticFilesStorage'
)
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': _staticfiles_backend,
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Почта (заявка на пробное, форма контактов) ---
# Все значения берутся из .env (см. .env.example как шаблон).
# STUDIO_NOTIFICATION_EMAIL — КУДА приходят письма (потом заменить на почту сестры).
# EMAIL_* — ОТКУДА шлёт SMTP (ящик + пароль приложения у Mail.ru / Яндекс / Gmail).
STUDIO_NOTIFICATION_EMAIL = os.environ.get('STUDIO_NOTIFICATION_EMAIL', '')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'web@studia.local')

# ЮKassa (демо / тестовый магазин). Значения — из .env.
YOOKASSA_SHOP_ID = os.environ.get('YOOKASSA_SHOP_ID', '')
YOOKASSA_SECRET_KEY = os.environ.get('YOOKASSA_SECRET_KEY', '')
YOOKASSA_PAYMENT_AMOUNT = Decimal('500.00')
YOOKASSA_PAYMENT_DESCRIPTION = 'Оплата занятий'
# Допустимый диапазон суммы в напоминании и при оплате через ЮKassa
PAYMENT_AMOUNT_MIN = Decimal('1.00')
PAYMENT_AMOUNT_MAX = Decimal('100000.00')
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000')

YOOKASSA_RETURN_URL = f'{SITE_URL.rstrip("/")}/oplata/vozvrat/'
YOOKASSA_ENABLED = bool(YOOKASSA_SHOP_ID and YOOKASSA_SECRET_KEY)

_smtp_ready = bool(EMAIL_HOST and EMAIL_HOST_USER and EMAIL_HOST_PASSWORD)
if _smtp_ready:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    if not DEFAULT_FROM_EMAIL or DEFAULT_FROM_EMAIL == 'web@studia.local':
        DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'web@studia.local'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'studio.mail': {
            'handlers': ['console'],
            'level': 'WARNING',
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/vhod/'
LOGIN_REDIRECT_URL = '/kabinet/'
LOGOUT_REDIRECT_URL = '/'

# ── Безопасность на боевом сервере (включается только при DEBUG=False) ──
# Локальная разработка (DEBUG=True) этими настройками не затрагивается.
if not DEBUG:
    # Перенаправлять весь трафик на HTTPS
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', True)
    # Cookie только по HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS (заставляет браузер всегда ходить по HTTPS). Включать, когда HTTPS уже настроен.
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Если сайт за обратным прокси (nginx и т.п.) — доверять заголовку протокола
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Домены, которым доверяем для CSRF (https). Заполнить в .env: CSRF_TRUSTED_ORIGINS=https://example.ru
    CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS', [])

# ── Оформление админки (Jazzmin) ──
JAZZMIN_SETTINGS = {
    'site_title': 'Vladimirka — администрирование',
    'site_header': 'Школа «Vladimirka»',
    'site_brand': 'Vladimirka',
    'welcome_sign': 'Панель администратора школы спорта и искусства «Vladimirka»',
    'copyright': 'Школа спорта и искусства «Vladimirka»',
    'search_model': ['studio.StudentProfile', 'studio.ParentProfile'],
    'show_ui_builder': False,
    'changeform_format': 'horizontal_tabs',
    'related_modal_active': True,
    'custom_css': 'studio/css/admin-jazzmin.css',
    'icons': {
        'auth': 'fas fa-users-cog',
        'auth.user': 'fas fa-user-shield',
        'auth.Group': 'fas fa-users',
        'studio.StudentProfile': 'fas fa-child',
        'studio.ParentProfile': 'fas fa-user-friends',
        'studio.DanceDirection': 'fas fa-music',
        'studio.DanceGroup': 'fas fa-layer-group',
        'studio.WeeklyClass': 'fas fa-calendar-day',
        'studio.Trainer': 'fas fa-chalkboard-teacher',
        'studio.StudioHall': 'fas fa-door-open',
        'studio.AchievementAlbum': 'fas fa-trophy',
        'studio.AchievementPhoto': 'fas fa-image',
        'studio.TrialApplication': 'fas fa-clipboard-list',
        'studio.ContactMessage': 'fas fa-envelope',
        'studio.LessonPayment': 'fas fa-credit-card',
        'studio.PaymentReminder': 'fas fa-bell',
        'studio.PaidPaymentReminder': 'fas fa-check-circle',
        'studio.PasswordResetCode': 'fas fa-key',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',
}

JAZZMIN_UI_TWEAKS = {
    'theme': 'default',
    'navbar': 'navbar-dark',
    'navbar_small_text': False,
    'sidebar': 'sidebar-dark-primary',
    'sidebar_nav_flat_style': True,
    'sidebar_nav_compact_style': True,
    'accent': 'accent-olive',
    'brand_colour': False,
    'no_navbar_border': True,
    'body_small_text': False,
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success',
    },
}
